version: 0.2

env:
  variables:
    SLS_DEBUG: '*'
    DURATION: '900'
    INFRA_PIPELINE_STACK: 'InfraPipelineStack'
    # Environment variables passed through from buildspec project
    #STAGE:        $STAGE
    #ACCOUNT_ID:   $ACCOUNT_ID
    #REGION:       $REGION
    #MFE_BUCKET_NAME: $MY_BUCKET_NAME
  secrets-manager:
    MY_NPM_TOKEN: MyNpmTokenSecret:Token

phases:
  install:
    runtime-versions:
      nodejs: 10
      python: 3.7

  pre_build:
    commands:
      - npm install -g serverless@1.73.0
      - pip3 install cfn-lint

  build:
    commands:
      - set -e
      - chmod u+x deploy-user.sh
      - |
        STACK=aws cloudformation list-stacks --stack-status-filter UPDATE_IN_PROGRESS | grep my-stack
        if [ -z "${STACK}" ] ; then
           #serverless deploy --stage production --region $REGION --accountId $ACCOUNT_ID
           sh deploy-user.sh
        else
            echo "An existing update in progress. PLease try again later"
        fi
      - echo "End of deployment"
